# Generated by Django 4.2 on 2025-01-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_messages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chatroom_images/'),
        ),
    ]
